import type { Metadata } from 'next';
import './globals.css';
import batman from '../../public/batman-black.png';
import search from '../../public/search-icon.png';
import Image from 'next/image';
import send from '../../public/send.png';
import { Inter, Poppins } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] });

export const metadata: Metadata = {
  title: 'Travel project',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${poppins.className}`}>
        {/* navbar */}
        <nav className='fixed top-0 w-full bg-white shadow-md z-50'>
          <div className='max-w-7xl mx-auto flex justify-around items-center px-5 h-[50px]'>
            {/* Logo */}
            <div className='flex items-center gap-2'>
              <Image src={batman} alt='batman' height={28} width={28} />
              <h1 className='text-black font-bold text-sm hover:text-green-600 cursor-pointer'>
                Go Wild
              </h1>
            </div>

            {/* Links */}
            <ul className='flex gap-6 font-medium text-gray-800 text-sm'>
              <li className='hover:text-green-600 cursor-pointer'>
                <Link href={'/'}>Home</Link>
              </li>
              <li className='hover:text-green-600 cursor-pointer'>
                <Link href={'/tour'}>Tour</Link>
              </li>
              <li className='hover:text-green-600 cursor-pointer'>
                Destinations
              </li>
              <li className='hover:text-green-600 cursor-pointer'>Blog</li>
              <Link
                href='/intelex-assigment'
                className='hover:text-green-600 cursor-pointe'>
                Assignmnet
              </Link>

              <li>
                <Image src={search} alt='search' height={16} width={16} />
              </li>
            </ul>

            {/* Button + send */}
            <div className='flex items-center '>
              <button className='text-start bg-amber-500 rounded-2xl px-4 py-1 text-xs font-medium text-white hover:bg-green-600 w-[120px] h-[30px]'>
                <Link
                  href='/booking'
                  className='hover:underline active:underline focus:underline hover:text-black'>
                  Book Now
                </Link>
              </button>
              <div className='bg-gray-100 rounded-full w-[26px] h-[26px] flex items-center justify-center absolute top-3 right-31 '>
                <Image src={send} alt='send' height={14} width={14} />
              </div>
            </div>
          </div>
        </nav>
        <div className='mt-12.5'>{children}</div>
        <div className='bg-[#1D231F] flex flex-col items-center justify-center py-25'>
          <div className='flex justify-around w-full'>
            <div className='flex '>
              <Image
                src='/onlinesupport.png'
                alt='online-support'
                width={60}
                height={60}
              />
              <div className='gap-2 p-2'>
                <h1 className='text-gray-400 font-bold text-xl'>
                  Need Any Support for Tours <br></br>& Travels ?
                </h1>
              </div>
              <div className='p-3'>
                <button className='text-black bg-gray-100 rounded-full p-2 hover:bg-green-400 hover:text-white'>
                  <Link href='/booking'> {`-->`}</Link>
                </button>
              </div>
            </div>
            <div className='flex '>
              <Image
                src='/vacation.png'
                alt='online-support'
                width={60}
                height={60}
              />
              <div className='gap-2 p-2'>
                <h1 className='text-gray-400 font-bold text-xl'>
                  Ready to get Started with <br></br>vactions !
                </h1>
              </div>
              <div className='p-3'>
                <button className='text-black bg-gray-100 rounded-full p-2 hover:bg-green-400 hover:text-white'>{`-->`}</button>
              </div>
            </div>
          </div>
          <div className='mt-8 w-full max-w-5xl'>
            <hr className='border-t-2 border-gray-600' />
          </div>
          <div className='flex justify-around mt-6 w-full'>
            {/* Column 1 */}
            <div className='flex flex-col'>
              <div className='p-2'>
                <h1 className='text-gray-400 font-bold'>About</h1>
                <h1 className='text-white text-sm mt-2'>
                  Exploring the world is not just about <br /> places, it’s
                  about the stories <br /> we collect
                </h1>
              </div>
              <div className='flex items-center  p-2'>
                <Image
                  src='/batman-gray.png'
                  alt='batman'
                  height={40}
                  width={40}
                />
                <h1 className='text-white font-bold text-md hover:text-green-600 cursor-pointer'>
                  Go Wild
                </h1>
              </div>
            </div>

            {/* Column 2 */}
            <div className='flex flex-col'>
              <div className='p-2'>
                <h1 className='text-gray-400 font-bold'>Services</h1>
                <ul className='text-white text-xs mt-1 font-semibold'>
                  <li className='mb-2 hover:text-green-600'>
                    Caravan soler Tent
                  </li>
                  <li className='mb-2 hover:text-green-600'>
                    Family Tent Camping
                  </li>
                  <li className='mb-2 hover:text-green-600'>
                    Classic Tent Camping
                  </li>
                  <li className='mb-2 hover:text-green-600'>
                    Wild Tent Camping
                  </li>
                  <li className='mb-2 hover:text-green-600'>
                    Small Cabin Wood
                  </li>
                </ul>
              </div>
            </div>
            {/* {column-3} */}
            <div className='flex flex-col'>
              <div className='p-2'>
                <ul className='text-white text-xs mt-3 font-semibold'>
                  <li className='mb-2 hover:text-green-600'>Need a Career ?</li>
                  <li className='mb-2 hover:text-green-600'>
                    Latest News and Blogs
                  </li>
                  <li className='mb-2 hover:text-green-600'>Core Features</li>
                  <li className='mb-2 hover:text-green-600'>Meet our Team</li>
                  <li className='mb-2 hover:text-green-600'>Explore More</li>
                </ul>
              </div>
            </div>
            {/* NewsLatter */}

            <div>
              <h1 className='text-gray-400 font-bold text-xl'>News Letter</h1>
              <h1 className='text-white text-sm mt-2'>
                Wander often, wonder always <br></br> subscribe for travel
                stories <br></br>straight to your inbox
              </h1>
              <input
                type='type'
                placeholder='Guest'
                className='text-xs text-white font-extralight border p-2  rounded-2xl border-white focus:outline-none mt-2'
              />
            </div>
          </div>
          <div className='mt-8 w-full max-w-5xl'>
            <hr className='border-t-2 border-gray-600' />
          </div>
        </div>
      </body>
    </html>
  );
}
